import type { QueryFilters } from "@tanstack/react-query"
import type { Address } from "viem"
import { getBalanceQueryKey, readContractQueryKey } from "wagmi/query"

import { isSameAddress } from "@/web3/evm/address"
import { standardErc20Abi } from "@/web3/evm/abi/erc20"

/**
 * The write type has confirmed onchain, deciding which read needs to be refreshed.
 */
export type EvmWriteKind =
  "native-transfer" | "token-transfer" | "token-approval"

export type EvmWriteInvalidationInput = {
  kind: EvmWriteKind
  chainId: number
  account: Address
  /**
   * Required for "token-transfer" and "token-approval".
   *
   * Must be `token.address` **registry canonical**, not raw address
   * transmitted by the caller: Wagmi's query key compares the string according to the correct casing,
   * So lowercase vs checksum will not match any query and invalidation is silent
   * do nothing.
   */
  tokenAddress?: Address
}

type MulticallContract = {
  address?: unknown
  chainId?: unknown
  functionName?: unknown
}

/**
 * Filter for queries that a write EVM ages.
 *
 * The query key is generated by Wagmi's own builder (`wagmi/query`).
 * matches the actual key that `useBalance` / `useReadContract` registers. Key intentionally quit
 * `args` to cover all owners/spenders of the same token, but still keep `functionName`
 * to not touch static read metadata (`name`/`symbol`/`decimals`).
 */
export function buildEvmWriteInvalidationFilters(
  input: EvmWriteInvalidationInput,
): QueryFilters[] {
  const { kind, chainId, account, tokenAddress } = input

  // Every transaction burns gas so the native balance is always changing — even
  // ERC-20 transfer and approval, which does not transfer any native tokens.
  const filters: QueryFilters[] = [
    { queryKey: getBalanceQueryKey({ address: account, chainId }) },
  ]

  if (kind === "native-transfer" || !tokenAddress) {
    return filters
  }

  const functionName = kind === "token-transfer" ? "balanceOf" : "allowance"

  filters.push({
    queryKey: readContractQueryKey({
      address: tokenAddress,
      abi: standardErc20Abi,
      functionName,
      chainId,
    }),
  })

  // Aggregate hook (useEvmBalances / useEvmAllowances) registers the query form
  // multicall, key contains `contracts` array so partial match by key is not filtered
  // be by token. Use predicate to only touch multicalls that are actually read
  // correct token + chain + function, instead of invalidating every multicall in
  // app.
  filters.push({
    predicate: (query) =>
      matchesMulticallRead(query.queryKey, {
        chainId,
        tokenAddress,
        functionName,
      }),
  })

  return filters
}

function matchesMulticallRead(
  queryKey: readonly unknown[],
  target: { chainId: number; tokenAddress: Address; functionName: string },
): boolean {
  const [root, params] = queryKey
  if (root !== "readContracts") return false

  const contracts = (params as { contracts?: unknown })?.contracts
  if (!Array.isArray(contracts)) return false

  return contracts.some((entry) => {
    const contract = entry as MulticallContract
    if (contract?.functionName !== target.functionName) return false
    if (
      contract?.chainId !== undefined &&
      contract.chainId !== target.chainId
    ) {
      return false
    }
    return isSameAddress(
      typeof contract?.address === "string" ? contract.address : null,
      target.tokenAddress,
    )
  })
}
